// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmmvverfblbhfjvetujy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtbXZ2ZXJmYmxiaGZqdmV0dWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDk1OTQsImV4cCI6MjA2NzkyNTU5NH0.GTP0GcFyJndYvpOwYeqlEg5JqQ1TZkRpSkZIBabiSDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});